select * from mimiciii.prescriptions where drug like '%idazolam%'
select * from mimiciii.prescriptions where drug like '%iazep%' 
select * from mimiciii.prescriptions where drug like '%lprazo%' 
select * from mimiciii.prescriptions where drug like '%exmedet%' 
select * from mimiciii.prescriptions where drug like '%ropofol%'
